= CodeReady Containers - OpenShift 4 on your Laptop
:icons:
:toc: macro
:toc-title:
:toclevels:

toc::[]

image:https://travis-ci.org/code-ready/crc.svg?branch=master["Travis CI Build Status", link="https://travis-ci.org/code-ready/crc"]
image:https://circleci.com/gh/code-ready/crc/tree/master.svg?style=svg["CircleCI Build Status", link="https://circleci.com/gh/code-ready/crc"]

[[intro-to-crc]]
== Introduction

This project is focused on bringing a minimal http://github.com/openshift/origin[OpenShift 4.0 or newer] cluster to your local laptop or desktop computer. 

If you are looking for a solution for running OpenShift 3.x, you will need tools such as `oc cluster up`, http://github.com/minishift/minishift[Minishift] or https://developers.redhat.com/products/cdk/overview/[CDK].

Check back for updates, we plan to have something available "soon".

[[documentation]]
== Documentation

- link:./developing.adoc[Developing CodeReady Containers]

[[community]]
== Community

Contributions, questions, and comments are all welcomed and encouraged!

You can reach the community by:

- Joining the #codeready channel on https://freenode.net/[Freenode IRC]

If you want to contribute, make sure to follow the link:CONTRIBUTING.adoc[contribution guidelines]
when you open issues or submit pull requests.

----------------------------

#### CodeReady Containers (CRC)

你可以参考git repo 中的docs,你也可以用一下方法生成一个漂亮的html docs 文件：
```
$ git clone https://github.com/code-ready/crc
$ cd crc
$ make build_docs
```

This will generate docs/build/master.html

##### 安装 slirp4netns
```
$ sudo yum install glib2-devel
$ sudo yum group install "Development Tools"
$ git clone https://github.com/rootless-containers/slirp4netns
$ cd slirp4netns
$ ./autogen.sh
$ ./configure --prefix=/usr
$ make
$ sudo make install
```
